# Generated by Django 2.2 on 2021-02-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.dribbble.com%2Fusers%2F1012566%2Fscreenshots%2F4187820%2Ftopic-2.jpg%3Fcompress%3D1%26resize%3D400x300&imgrefurl=https%3A%2F%2Fdribbble.com%2Fshots%2F4187820-404-Food-Not-Found&tbnid=CuU3H4BFM5KPLM&vet=12ahUKEwju0vOpzufuAhVIKrcAHdNpAv4QMygAegUIARCbAQ..i&docid=0k5rhoJHXvlkdM&w=400&h=300&q=placeholder%20food%20images&ved=2ahUKEwju0vOpzufuAhVIKrcAHdNpAv4QMygAegUIARCbAQ', max_length=500),
        ),
    ]
